FROM chwang733/fastai_v1:v3-gpu

WORKDIR /home/user/

#add additional artifacts

#COPY  --chown=user:user ./files/ComputerVision ./ComputerVision
#COPY  --chown=user:user ./files/data  ./data
#COPY  --chown=user:user ./files/.fastai  ./.fastai
#COPY  --chown=user:user ./files/.torch ./.torch


